version: '3.8'

services:
  server:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: backend-app
    command: npm start
    ports:
      - "3000:3000"
    

  client:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    command: npm run dev
    image: frontend-app
    
    ports:
      - "5173:5173"